# Generated by Django 4.1.4 on 2022-12-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_author_date_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Farsi', 'Farsi')], default='English', max_length=7),
        ),
    ]
