# Generated by Django 4.1.4 on 2022-12-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_bookinstance_borrower_alter_author_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
