# Generated by Django 4.1.4 on 2022-12-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Characters <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a> ', max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
